# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hseagent_sdk.models.observation_type import ObservationType

class TestObservationType(unittest.TestCase):
    """ObservationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ObservationType:
        """Test ObservationType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ObservationType`
        """
        model = ObservationType()
        if include_optional:
            return ObservationType(
                id = 56,
                sections = [
                    hseagent_sdk.models.section.Section(
                        id = 56, 
                        name = '', 
                        code = '', 
                        description = '', 
                        section_type = hseagent_sdk.models.section_type.SectionType(
                            id = 56, 
                            name = '', 
                            code = '', 
                            description = '', ), )
                    ],
                name = '',
                description = '',
                code = '',
                required = True,
                var_schema = None,
                value_type = None,
                category = hseagent_sdk.models.observation_category.ObservationCategory(
                    id = 56, 
                    name = '', 
                    description = '', 
                    code = '', ),
                unit = '',
                hint = '',
                examination_types = [
                    hseagent_sdk.models.examination_type.ExaminationType(
                        id = 56, 
                        name = '', 
                        parent = '', 
                        description = '', 
                        code = '', )
                    ]
            )
        else:
            return ObservationType(
                id = 56,
                sections = [
                    hseagent_sdk.models.section.Section(
                        id = 56, 
                        name = '', 
                        code = '', 
                        description = '', 
                        section_type = hseagent_sdk.models.section_type.SectionType(
                            id = 56, 
                            name = '', 
                            code = '', 
                            description = '', ), )
                    ],
                name = '',
                category = hseagent_sdk.models.observation_category.ObservationCategory(
                    id = 56, 
                    name = '', 
                    description = '', 
                    code = '', ),
                examination_types = [
                    hseagent_sdk.models.examination_type.ExaminationType(
                        id = 56, 
                        name = '', 
                        parent = '', 
                        description = '', 
                        code = '', )
                    ],
        )
        """

    def testObservationType(self):
        """Test ObservationType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
