# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hseagent_sdk.models.patched_clinic_profile import PatchedClinicProfile

class TestPatchedClinicProfile(unittest.TestCase):
    """PatchedClinicProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchedClinicProfile:
        """Test PatchedClinicProfile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedClinicProfile`
        """
        model = PatchedClinicProfile()
        if include_optional:
            return PatchedClinicProfile(
                name = '',
                phone = '',
                mobile = '09480728880',
                website = '',
                address = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return PatchedClinicProfile(
        )
        """

    def testPatchedClinicProfile(self):
        """Test PatchedClinicProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
