# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hseagent_sdk.models.blank_enum import BlankEnum

class TestBlankEnum(unittest.TestCase):
    """BlankEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlankEnum(self):
        """Test BlankEnum"""
        # inst = BlankEnum()

if __name__ == '__main__':
    unittest.main()
