# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hseagent_sdk.api.ai_api import AiApi


class TestAiApi(unittest.TestCase):
    """AiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AiApi()

    def tearDown(self) -> None:
        pass

    def test_ai_list(self) -> None:
        """Test case for ai_list

        """
        pass

    def test_ai_retrieve(self) -> None:
        """Test case for ai_retrieve

        """
        pass

    def test_ai_update(self) -> None:
        """Test case for ai_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
