# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hseagent_sdk.api.actions_api import ActionsApi


class TestActionsApi(unittest.TestCase):
    """ActionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ActionsApi()

    def tearDown(self) -> None:
        pass

    def test_actions_create(self) -> None:
        """Test case for actions_create

        """
        pass

    def test_actions_list(self) -> None:
        """Test case for actions_list

        """
        pass

    def test_actions_retrieve(self) -> None:
        """Test case for actions_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
