# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.hse_reports_api import HseReportsApi


class TestHseReportsApi(unittest.TestCase):
    """HseReportsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HseReportsApi()

    def tearDown(self) -> None:
        pass

    def test_hse_reports_approve_create(self) -> None:
        """Test case for hse_reports_approve_create

        """
        pass

    def test_hse_reports_create(self) -> None:
        """Test case for hse_reports_create

        """
        pass

    def test_hse_reports_destroy(self) -> None:
        """Test case for hse_reports_destroy

        """
        pass

    def test_hse_reports_download_retrieve(self) -> None:
        """Test case for hse_reports_download_retrieve

        """
        pass

    def test_hse_reports_list(self) -> None:
        """Test case for hse_reports_list

        """
        pass

    def test_hse_reports_partial_update(self) -> None:
        """Test case for hse_reports_partial_update

        """
        pass

    def test_hse_reports_retrieve(self) -> None:
        """Test case for hse_reports_retrieve

        """
        pass

    def test_hse_reports_update(self) -> None:
        """Test case for hse_reports_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
