# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.patched_physician import PatchedPhysician

class TestPatchedPhysician(unittest.TestCase):
    """PatchedPhysician unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchedPhysician:
        """Test PatchedPhysician
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedPhysician`
        """
        model = PatchedPhysician()
        if include_optional:
            return PatchedPhysician(
                id = 56,
                first_name = '',
                last_name = '',
                gender = None,
                national_code = '',
                mobile = '09480728880',
                email = '',
                medical_code = '',
                specialty = '',
                is_active = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                occupational_clinic = 56
            )
        else:
            return PatchedPhysician(
        )
        """

    def testPatchedPhysician(self):
        """Test PatchedPhysician"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
