# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hseagent_sdk.models.callback_token_auth import CallbackTokenAuth

class TestCallbackTokenAuth(unittest.TestCase):
    """CallbackTokenAuth unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CallbackTokenAuth:
        """Test CallbackTokenAuth
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CallbackTokenAuth`
        """
        model = CallbackTokenAuth()
        if include_optional:
            return CallbackTokenAuth(
                email = '',
                mobile = '+680728880015',
                token = '012345'
            )
        else:
            return CallbackTokenAuth(
                token = '012345',
        )
        """

    def testCallbackTokenAuth(self):
        """Test CallbackTokenAuth"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
