# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hseagent_sdk.models.action_ai_status_enum import ActionAIStatusEnum

class TestActionAIStatusEnum(unittest.TestCase):
    """ActionAIStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActionAIStatusEnum(self):
        """Test ActionAIStatusEnum"""
        # inst = ActionAIStatusEnum()

if __name__ == '__main__':
    unittest.main()
