# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.examinations_api import ExaminationsApi


class TestExaminationsApi(unittest.TestCase):
    """ExaminationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExaminationsApi()

    def tearDown(self) -> None:
        pass

    def test_examinations_create(self) -> None:
        """Test case for examinations_create

        """
        pass

    def test_examinations_destroy(self) -> None:
        """Test case for examinations_destroy

        """
        pass

    def test_examinations_list(self) -> None:
        """Test case for examinations_list

        """
        pass

    def test_examinations_partial_update(self) -> None:
        """Test case for examinations_partial_update

        """
        pass

    def test_examinations_retrieve(self) -> None:
        """Test case for examinations_retrieve

        """
        pass

    def test_examinations_update(self) -> None:
        """Test case for examinations_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
