# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.process import Process

class TestProcess(unittest.TestCase):
    """Process unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Process:
        """Test Process
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Process`
        """
        model = Process()
        if include_optional:
            return Process(
                id = 56,
                name = '',
                description = '',
                hazards = [
                    openapi_client.models.observation_type.ObservationType(
                        id = 56, 
                        sections = [
                            openapi_client.models.section.Section(
                                id = 56, 
                                name = '', 
                                code = '', 
                                description = '', 
                                section_type = openapi_client.models.section_type.SectionType(
                                    id = 56, 
                                    name = '', 
                                    code = '', 
                                    description = '', ), )
                            ], 
                        name = '', 
                        description = '', 
                        code = '', 
                        required = True, 
                        schema = null, 
                        value_type = null, 
                        category = null, 
                        unit = '', 
                        hint = '', 
                        examination_types = [
                            openapi_client.models.examination_type.ExaminationType(
                                id = 56, 
                                name = '', 
                                parent = '', 
                                description = '', 
                                code = '', )
                            ], )
                    ],
                hazard_ids = [
                    56
                    ],
                organization = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return Process(
                id = 56,
                name = '',
                hazards = [
                    openapi_client.models.observation_type.ObservationType(
                        id = 56, 
                        sections = [
                            openapi_client.models.section.Section(
                                id = 56, 
                                name = '', 
                                code = '', 
                                description = '', 
                                section_type = openapi_client.models.section_type.SectionType(
                                    id = 56, 
                                    name = '', 
                                    code = '', 
                                    description = '', ), )
                            ], 
                        name = '', 
                        description = '', 
                        code = '', 
                        required = True, 
                        schema = null, 
                        value_type = null, 
                        category = null, 
                        unit = '', 
                        hint = '', 
                        examination_types = [
                            openapi_client.models.examination_type.ExaminationType(
                                id = 56, 
                                name = '', 
                                parent = '', 
                                description = '', 
                                code = '', )
                            ], )
                    ],
                hazard_ids = [
                    56
                    ],
                organization = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testProcess(self):
        """Test Process"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
