# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hseagent_sdk.api.physicians_api import PhysiciansApi


class TestPhysiciansApi(unittest.TestCase):
    """PhysiciansApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PhysiciansApi()

    def tearDown(self) -> None:
        pass

    def test_physicians_create(self) -> None:
        """Test case for physicians_create

        """
        pass

    def test_physicians_destroy(self) -> None:
        """Test case for physicians_destroy

        """
        pass

    def test_physicians_list(self) -> None:
        """Test case for physicians_list

        """
        pass

    def test_physicians_partial_update(self) -> None:
        """Test case for physicians_partial_update

        """
        pass

    def test_physicians_retrieve(self) -> None:
        """Test case for physicians_retrieve

        """
        pass

    def test_physicians_update(self) -> None:
        """Test case for physicians_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
