# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.hazard_evaluations_api import HazardEvaluationsApi


class TestHazardEvaluationsApi(unittest.TestCase):
    """HazardEvaluationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HazardEvaluationsApi()

    def tearDown(self) -> None:
        pass

    def test_hazard_evaluations_create(self) -> None:
        """Test case for hazard_evaluations_create

        """
        pass

    def test_hazard_evaluations_destroy(self) -> None:
        """Test case for hazard_evaluations_destroy

        """
        pass

    def test_hazard_evaluations_list(self) -> None:
        """Test case for hazard_evaluations_list

        """
        pass

    def test_hazard_evaluations_partial_update(self) -> None:
        """Test case for hazard_evaluations_partial_update

        """
        pass

    def test_hazard_evaluations_retrieve(self) -> None:
        """Test case for hazard_evaluations_retrieve

        """
        pass

    def test_hazard_evaluations_update(self) -> None:
        """Test case for hazard_evaluations_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
