# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hseagent_sdk.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_auth_email_create(self) -> None:
        """Test case for auth_email_create

        """
        pass

    def test_auth_mobile_create(self) -> None:
        """Test case for auth_mobile_create

        """
        pass

    def test_auth_token_create(self) -> None:
        """Test case for auth_token_create

        """
        pass

    def test_auth_verify_create(self) -> None:
        """Test case for auth_verify_create

        """
        pass

    def test_auth_verify_email_create(self) -> None:
        """Test case for auth_verify_email_create

        """
        pass

    def test_auth_verify_mobile_create(self) -> None:
        """Test case for auth_verify_mobile_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
