# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hseagent_sdk.api.departments_api import DepartmentsApi


class TestDepartmentsApi(unittest.TestCase):
    """DepartmentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DepartmentsApi()

    def tearDown(self) -> None:
        pass

    def test_departments_create(self) -> None:
        """Test case for departments_create

        """
        pass

    def test_departments_destroy(self) -> None:
        """Test case for departments_destroy

        """
        pass

    def test_departments_list(self) -> None:
        """Test case for departments_list

        """
        pass

    def test_departments_partial_update(self) -> None:
        """Test case for departments_partial_update

        """
        pass

    def test_departments_retrieve(self) -> None:
        """Test case for departments_retrieve

        """
        pass

    def test_departments_update(self) -> None:
        """Test case for departments_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
