# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hseagent_sdk.api.profile_api import ProfileApi


class TestProfileApi(unittest.TestCase):
    """ProfileApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProfileApi()

    def tearDown(self) -> None:
        pass

    def test_profile_retrieve(self) -> None:
        """Test case for profile_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
