# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hseagent_sdk.models.callback_token_verification import CallbackTokenVerification

class TestCallbackTokenVerification(unittest.TestCase):
    """CallbackTokenVerification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CallbackTokenVerification:
        """Test CallbackTokenVerification
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CallbackTokenVerification`
        """
        model = CallbackTokenVerification()
        if include_optional:
            return CallbackTokenVerification(
                email = '',
                mobile = '+680728880015',
                token = '012345'
            )
        else:
            return CallbackTokenVerification(
                token = '012345',
        )
        """

    def testCallbackTokenVerification(self):
        """Test CallbackTokenVerification"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
