# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hseagent_sdk.models.section_type import SectionType

class TestSectionType(unittest.TestCase):
    """SectionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SectionType:
        """Test SectionType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SectionType`
        """
        model = SectionType()
        if include_optional:
            return SectionType(
                id = 56,
                name = '',
                code = '',
                description = ''
            )
        else:
            return SectionType(
                id = 56,
                name = '',
        )
        """

    def testSectionType(self):
        """Test SectionType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
