# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.observation_type_value_type import ObservationTypeValueType

class TestObservationTypeValueType(unittest.TestCase):
    """ObservationTypeValueType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ObservationTypeValueType:
        """Test ObservationTypeValueType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ObservationTypeValueType`
        """
        model = ObservationTypeValueType()
        if include_optional:
            return ObservationTypeValueType(
            )
        else:
            return ObservationTypeValueType(
        )
        """

    def testObservationTypeValueType(self):
        """Test ObservationTypeValueType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
