# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hseagent_sdk.models.section import Section

class TestSection(unittest.TestCase):
    """Section unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Section:
        """Test Section
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Section`
        """
        model = Section()
        if include_optional:
            return Section(
                id = 56,
                name = '',
                code = '',
                description = '',
                section_type = hseagent_sdk.models.section_type.SectionType(
                    id = 56, 
                    name = '', 
                    code = '', 
                    description = '', )
            )
        else:
            return Section(
                id = 56,
                name = '',
                section_type = hseagent_sdk.models.section_type.SectionType(
                    id = 56, 
                    name = '', 
                    code = '', 
                    description = '', ),
        )
        """

    def testSection(self):
        """Test Section"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
