# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hseagent_sdk.api.observation_types_api import ObservationTypesApi


class TestObservationTypesApi(unittest.TestCase):
    """ObservationTypesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ObservationTypesApi()

    def tearDown(self) -> None:
        pass

    def test_observation_types_list(self) -> None:
        """Test case for observation_types_list

        """
        pass

    def test_observation_types_retrieve(self) -> None:
        """Test case for observation_types_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
