# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.null_enum import NullEnum

class TestNullEnum(unittest.TestCase):
    """NullEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNullEnum(self):
        """Test NullEnum"""
        # inst = NullEnum()

if __name__ == '__main__':
    unittest.main()
