# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.branches_api import BranchesApi


class TestBranchesApi(unittest.TestCase):
    """BranchesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BranchesApi()

    def tearDown(self) -> None:
        pass

    def test_branches_create(self) -> None:
        """Test case for branches_create

        """
        pass

    def test_branches_destroy(self) -> None:
        """Test case for branches_destroy

        """
        pass

    def test_branches_list(self) -> None:
        """Test case for branches_list

        """
        pass

    def test_branches_partial_update(self) -> None:
        """Test case for branches_partial_update

        """
        pass

    def test_branches_retrieve(self) -> None:
        """Test case for branches_retrieve

        """
        pass

    def test_branches_update(self) -> None:
        """Test case for branches_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
