# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hseagent_sdk.models.hse_report_status_enum import HSEReportStatusEnum

class TestHSEReportStatusEnum(unittest.TestCase):
    """HSEReportStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHSEReportStatusEnum(self):
        """Test HSEReportStatusEnum"""
        # inst = HSEReportStatusEnum()

if __name__ == '__main__':
    unittest.main()
