# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.clinic_profile_api import ClinicProfileApi


class TestClinicProfileApi(unittest.TestCase):
    """ClinicProfileApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ClinicProfileApi()

    def tearDown(self) -> None:
        pass

    def test_clinic_profile_partial_update(self) -> None:
        """Test case for clinic_profile_partial_update

        """
        pass

    def test_clinic_profile_retrieve(self) -> None:
        """Test case for clinic_profile_retrieve

        """
        pass

    def test_clinic_profile_update(self) -> None:
        """Test case for clinic_profile_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
