# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.employment_history_api import EmploymentHistoryApi


class TestEmploymentHistoryApi(unittest.TestCase):
    """EmploymentHistoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmploymentHistoryApi()

    def tearDown(self) -> None:
        pass

    def test_employment_history_create(self) -> None:
        """Test case for employment_history_create

        """
        pass

    def test_employment_history_destroy(self) -> None:
        """Test case for employment_history_destroy

        """
        pass

    def test_employment_history_list(self) -> None:
        """Test case for employment_history_list

        """
        pass

    def test_employment_history_partial_update(self) -> None:
        """Test case for employment_history_partial_update

        """
        pass

    def test_employment_history_retrieve(self) -> None:
        """Test case for employment_history_retrieve

        """
        pass

    def test_employment_history_update(self) -> None:
        """Test case for employment_history_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
