# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hseagent_sdk.api.roles_api import RolesApi


class TestRolesApi(unittest.TestCase):
    """RolesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RolesApi()

    def tearDown(self) -> None:
        pass

    def test_roles_create(self) -> None:
        """Test case for roles_create

        """
        pass

    def test_roles_destroy(self) -> None:
        """Test case for roles_destroy

        """
        pass

    def test_roles_list(self) -> None:
        """Test case for roles_list

        """
        pass

    def test_roles_partial_update(self) -> None:
        """Test case for roles_partial_update

        """
        pass

    def test_roles_retrieve(self) -> None:
        """Test case for roles_retrieve

        """
        pass

    def test_roles_update(self) -> None:
        """Test case for roles_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
