# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ActionAIStatusEnum(str, Enum):
    """
    * `hold` - نگه داشته شده * `pending` - در انتظار * `in_progress` - در حال انجام * `done` - انجام شده
    """

    """
    allowed enum values
    """
    HOLD = 'hold'
    PENDING = 'pending'
    IN_PROGRESS = 'in_progress'
    DONE = 'done'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ActionAIStatusEnum from a JSON string"""
        return cls(json.loads(json_str))


