# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class HSEReportStatusEnum(str, Enum):
    """
    * `awaiting_clinic` - در انتظار بررسی کلینیک * `awaiting_hse` - در انتظار بررسی کارشناس HSE * `completed` - تکمیل شده
    """

    """
    allowed enum values
    """
    AWAITING_CLINIC = 'awaiting_clinic'
    AWAITING_HSE = 'awaiting_hse'
    COMPLETED = 'completed'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HSEReportStatusEnum from a JSON string"""
        return cls(json.loads(json_str))


