# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MilitaryServiceEnum(str, Enum):
    """
    * `` - --- * `medical_exemption` - معافیت پزشکی * `nonmedical_exemption` - معافیت غیر پزشکی * `eligible` - مشمول * `serving` - در حال خدمت * `completed` - پایان خدمت
    """

    """
    allowed enum values
    """
    MEDICAL_EXEMPTION = 'medical_exemption'
    NONMEDICAL_EXEMPTION = 'nonmedical_exemption'
    ELIGIBLE = 'eligible'
    SERVING = 'serving'
    COMPLETED = 'completed'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MilitaryServiceEnum from a JSON string"""
        return cls(json.loads(json_str))


