# coding: utf-8

"""
    My API

    Description of my API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class EducationLevelEnum(str, Enum):
    """
    * `` - --- * `below_diploma` - زیر دیپلم * `diploma` - دیپلم * `associate` - کاردانی * `bachelor` - کارشناسی * `master` - کارشناسی ارشد * `phd` - دکتری
    """

    """
    allowed enum values
    """
    BELOW_DIPLOMA = 'below_diploma'
    DIPLOMA = 'diploma'
    ASSOCIATE = 'associate'
    BACHELOR = 'bachelor'
    MASTER = 'master'
    PHD = 'phd'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EducationLevelEnum from a JSON string"""
        return cls(json.loads(json_str))


